### ISSUE TITLE
Access to gamesdb.gog.com

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#10]
According to logs, GOG tries to lookup additional game info from ` https://gamesdb.gog.com:443/platforms/<PLATFORM_ID>/external_releases/<GAME_ID>`

Is there any way to:
* disable access to gamesdb and provide JSON with info by integration
* or add information to Games DB?

**Comment by apaulouski** [comment]
As of yet there is no other way for GLX2.0to get game info other than via gamesdb. Missing games info will get fulfilled after some time.

**Comment by Stevoisiak** [comment]
Are there any plans for a system to submit missing cover art, such as on IGDB or GiantBomb?

**Comment by Stevoisiak** [comment]
I think some of the game data originates from [IGDB](https://www.igdb.com). When I encountered a duplicate search result in Galaxy for *Shower With Your Dad Simulator*, I was able to locate the same [duplicate entry](https://www.igdb.com/games/duplicate-shower-with-your-dad-simulator-2015-do-you-still-shower-with-your-dad) in IGDB. (This has since been reported & corrected in IGDB)

**Comment by rogersachan** [comment]
@Mixaill as far as I can tell, GamesDB seems to sync info from IGDB. I had an issue the other day where GOG Galaxy associated the Steam game [Slapshot](https://store.steampowered.com/app/707680/Slapshot/) with a much older NHL game. I added info regarding the game to IGDB and soon after GOG Galaxy had this info as well.

**Comment by apaulouski** [comment]
Any missing games should be reported with GLX: cogwheel menu -> Report Issue
