### ISSUE TITLE
Request - Nintendo switch account support

### ISSUE THREAD

**Issue by AucuneInspiexe** [gogcom/galaxy-integrations-python-api#178]
Hi ! Do GOG Galaxy can do the support of an nintendo account ?

**Comment by ShaunV2** [comment]
I doubt it, there would have to be a website with this information available to the public and an API to access it which I'm not sure exists.

**Comment by CDJack** [comment]
Every Nintendo Switch owner has an account that can be accessed via the website: https://accounts.nintendo.com/ You cannot check your games directly on it, but this information is probably attached to it because, first of all, there is such a list of games in the console Secondly, when you are logged in, when you enter individual games, you get information whether you already have it.
As for the API, take a look here: https://dev.to/mathewthe2/intro-to-nintendo-switch-rest-api-2cm7

**Comment by Vlkos77** [comment]
Yes plssssss make it plssssss

**Comment by mbanczerowski** [comment]
Thanks for all your input. I'm closing this thread as it does not directly refer to the API.

For further discussion should be held within any community space for example: https://github.com/Mixaill/awesome-gog-galaxy/issues/19
