### ISSUE TITLE
importing friends recommendations list (Steam username leak)

### ISSUE THREAD

**Issue by FierySama** [gogcom/galaxy-integrations-python-api#31]
If possible, please do not show the usernames on steam through the recommendation list. I can see that one of my friends in the recommendation list shows his full username he uses to login instead of his nickname. Please use the steam nickname only that they have at the time instead, my steam login username is my first and last name from my own stupidity from when i was 14--and as steam never ever allows us to change usernames, this is really bad news for people who want to keep their private login username well... private. This means if you have many users using gog galaxy and connect steam, your friends on steam will be able to see your login username through the recommendation tab on gog galaxy, which could contain personal information such as people's email addresses if they created their steam account in 2003/2004, or their first and last name like me.

Please think about it, thank you.

**Comment by apaulouski** [comment]
Thanks for your feedback. Your steam account name was supposed to be seen only by you and no-one else. This is definitely a problem and it's something we are already looking at and hope to fix this in the nearest future.
I'm sorry for the inconvenience it caused.

**Comment by FierySama** [comment]
Thank you so much @apaulouski . I'm so happy to hear this, I love what you are doing in making Gog Galaxy 2.0 better with the Python Api. Have a good one.

**Comment by RaptorPharaoh** [comment]
@apaulouski @FierySama I have the same problem, in my friend list recommendation appear me a friend from steam with his EMAIL, now i know his email :(

**Comment by apaulouski** [comment]
This has been fixed in both:
* SteamPlugin v0.29.3 (FriendsOfGalaxy/galaxy-integration-steam@03e26c3168f3d12d24de5d2db948b9109a8dc0c6)
* UplayPlugin v0.40 (FriendsOfGalaxy/galaxy-integration-uplay@1009967e5f4bb864e73618e12bb052084a98b8a4)
Other plugins did not returned any private info.

To force use proper name:
- disconnect a platform
- make sure proper version of the plugin is used (`version` could be found in plugin's `manifest.json` located in %LOCALAPPDATA%\GOG.com\Galaxy\plugins\installed)
- if old version is still in use, remove plugin folder. Updated version will be redownloaded automatically
- connect the platform again

Once again, I'm sorry for the inconvenience it caused.
