### ISSUE TITLE
Create custom platforms.

### ISSUE THREAD

**Issue by Lucasthoelke** [gogcom/galaxy-integrations-python-api#66]
Would it be possible that we can create custom platforms?

**Comment by apaulouski** [comment]
Definitions for new platforms (e.g. `Test`) were added only in python API, yet Galaxy Client update was needed for them to be supported. You could try now.
AFAIK `generic` should not be used at all.

**Comment by ivellios** [comment]
There are no `generic` platforms used/visible/available at all. Then which one should be used for the plugin which is supposed to automatically add games from my own list (like list of games I have on DVDs)? 

Having `Custom1`-`Custom10` might be one of the solutions. Also in the most recent version of the API I don't see `test` available under `Platform` class, but I can confirm that using `test` string will work. Should it be added there?

**Comment by ivellios** [comment]
Also `test` type crashes all the time upon `Connect`. Where will I find debug for that?

Should I provide Authentication in case of `test` type?

**Comment by apaulouski** [comment]
All logs (you will be interested in the `GalaxyClient.log` and `plugin-test-...log`) are located in `c:\ProgramData\GOG.com\Galaxy\logs\` on Windows. 
Plugin needs at least `authenticate` and one of the feature methods (e.g. `get_local_games`), even if they return no real data. Otherwise GLX is stuck on launching it. It's a know issue, but has a low priority, as this should never happen in a real world with a working plugin.
We'll consider adding `Custom` platforms in near future. As a workaround you can manually `Mark as owned` these games in the GLX Client, or use any spare platforms.

**Comment by Countryen** [comment]
+1 for custom IDs / a "generic" ID

BTW: As of April, 8, I've got "test" running but not "generic" (as said).
Also "unknown" doesn't work, too.
(Maybe remove them from the "List of IDs if they are not meant to be used"?)

Thanks for the info about the logs, please add that to the documentation / readme.

**Comment by mbanczerowski** [comment]
I've added discussed proposals in 9745dcd8ef187b982cb92d52403c0d84335be0cf
`Custom` platform(s) need to wait for now.

**Comment by mbanczerowski** [comment]
Custom platforms issue waits for resolution in the task mentioned above. Thanks for discussion and feedback.
